library:
  source-dirs: src
license-file: LICENSE
build-type: Simple
maintainer: Chris Stryczynski
dependencies:
- base >=4.10 && <4.11
- orgmode-parse
- attoparsec
- text
- pretty-simple
- unordered-containers 
- thyme
- old-locale
name: orgmode-parse-print
version: '0.1.0.0'
extra-source-files: ChangeLog.md
author: Chris Stryczynski
license: BSD3
